services:
  ctbrec:
    build:
      context: .
      args:
        - CTBVER=${CTBVER}
    image: ghcr.io/justsudo/ctbrec-alpine:${CTBVER}
    container_name: ctbrec
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - "${CONFIG}:/app/config"
      - "${MEDIA}:/app/media"
    ports:
      - 18080:8080
      - 18443:8443
    restart: "unless-stopped"
